name: torch-merf2
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - alsa-lib=1.2.8
  - binutils=2.38
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - bzip2=1.0.8
  - c-compiler=1.5.2
  - ca-certificates=2023.08.22
  - cuda=11.7
  - ocl-icd-system
  - cxx-compiler=1.5.2
  - dbus=1.13.18
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - gcc=11.2.0
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gds-tools=1.5.0.59
  - gettext=0.21.1
  - glib=2.78.1
  - glib-tools=2.78.1
  - gmp=6.2.1
  - gxx=11.2.0
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - icu=73.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.38
  - libcublas=12.0.1.189
  - libcublas-dev=12.0.1.189
  - libcufft=11.0.0.21
  - libcufft-dev=11.0.0.21
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcusolver=11.4.2.57
  - libcusolver-dev=11.4.2.57
  - libcusparse=12.0.0.76
  - libcusparse-dev=12.0.0.76
  - libedit=3.1.20221030
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=13.2.0
  - libglib=2.78.1
  - libgomp=13.2.0
  - libiconv=1.17
  - libnpp=12.0.0.30
  - libnpp-dev=12.0.0.30
  - libnuma=2.0.16
  - libnvjitlink=12.0.76
  - libnvjitlink-dev=12.0.76
  - libnvjpeg=12.0.0.28
  - libnvjpeg-dev=12.0.0.28
  - libpng=1.6.39
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxkbfile=1.1.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - ncurses=6.4
  - nsight-compute=2022.4.0.15
  - nspr=4.35
  - nss=3.89.1
  - ocl-icd=2.3.1
  - openssl=3.0.12
  - pcre2=10.42
  - pip=23.3
  - pip:
      - "git+https://github.com/NVlabs/nvdiffrast/"
  - python=3.9.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sysroot_linux-64=2.17
  - tk=8.6.12
  - wayland=1.22.0
  - wheel=0.41.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.40
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.3
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.19.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - dearpygui==1.10.1
      - fonttools==4.44.3
      - idna==3.4
      - imageio==2.32.0
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.9.0
      - lpips==0.1.4
      - markdown-it-py==3.0.0
      - matplotlib==3.8.1
      - mdurl==0.1.2
      - ninja==1.11.1.1
      - numpy==1.26.2
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.3
      - pillow==10.0.1
      - protobuf==4.25.1
      - pygments==2.16.1
      - pymcubes==0.1.4
      - pymeshlab==2022.2.post4
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - requests==2.31.0
      - rich==13.7.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - six==1.16.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - torch==2.0.0
      - torchvision==0.15.1
      - torch-efficient-distloss==0.1.3
      - torch-ema==0.3
      - torchmetrics==1.2.0
      - tqdm==4.66.1
      - trimesh==4.0.4
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - xatlas==0.0.8
      - zipp==3.17.0
